### ISSUE TITLE
DLL Support Broken?

### ISSUE THREAD

**Issue by t0ms0nic** [thesupersonic16/mania-mod-loader#1]
[MainMemory's SMPS Music mod](https://gamebanana.com/gamefiles/6018), which is the only DLL mod so far, seems to not work in any capacity for this update to the Mod Loader. Trying to load the game with it just gives an error message about the mod type not being supported before loading the game with any other mods active and working, so I'm assuming that DLL support in general might have been broken.

Not sure if this is something easily fixed, but figured it was noteworthy in case this was going to be the Mod Loader for the foreseeable future.

**Comment by thesupersonic16** [comment]
It saying "Not a valid mod file." i think is a bug, It should be saying "Not built for the current version of the game.". This is caused by the mod being compiled using an older version of the ModLoader, Updating the DLL with the new addresses and with this ModLoader should get it to load. And If i feel like it, I might also get that mod updated to this ModLoader. I have not tested DLL support yet, But I'm sure it will work if the mod supports this version of the modloader.

**Comment by thesupersonic16** [comment]
DLL Loading works. You just need a mod that is compiled using this modloader.
